# Generated by Django 3.2.5 on 2021-07-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='email',
        ),
    ]
