# Generated by Django 3.2.5 on 2021-07-20 17:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozio_app', '0002_provider_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='point',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
