# Generated by Django 3.2.5 on 2021-07-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozio_app', '0002_remove_provider_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
