# Generated by Django 3.2.5 on 2021-07-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozio_app', '0003_provider_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(default='babayega@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
