# Generated by Django 3.2.5 on 2021-07-21 07:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozio_app', '0005_servicearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
