# Generated by Django 3.2.5 on 2021-07-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mozio_app', '0006_provider_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='point',
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mozio_app.provider'),
        ),
    ]
