# Generated by Django 3.2.5 on 2021-07-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
